image: node:8.11.1

pipelines:
  default:
    - step:
        caches:
          - node
        script:
          - npm install
          - npm test
          - git push -f https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git HEAD:master